package org.nm.gdrive_backup.adapter.in.javafx;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import javafx.collections.ListChangeListener;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import javafx.stage.Window;

/**
 * The application icon for the title bar and the taskbar. The PNGs under {@code /icons} are generated by
 * {@code tools/GenerateAppIcon.java}, which also writes the .ico the Windows package embeds in the .exe.
 */
public final class AppIcons {

	private static final int[] SIZES = {16, 24, 32, 48, 64, 128, 256};

	private static boolean installed;

	private AppIcons() {
	}

	/**
	 * Gives the icon to every window that has none of its own, now and as they open: the main window, the
	 * Settings dialog and the alerts, which are all separate stages. Call on the FX thread.
	 */
	public static void install() {
		if (installed) {
			return;
		}
		installed = true;
		List<Image> icons = load();
		Window.getWindows().forEach(window -> apply(window, icons));
		Window.getWindows().addListener((ListChangeListener<Window>) change -> {
			while (change.next()) {
				change.getAddedSubList().forEach(window -> apply(window, icons));
			}
		});
	}

	private static void apply(Window window, List<Image> icons) {
		if (window instanceof Stage stage && stage.getIcons().isEmpty()) {
			stage.getIcons().addAll(icons);
		}
	}

	private static List<Image> load() {
		List<Image> icons = new ArrayList<>();
		for (int size : SIZES) {
			try (InputStream stream = AppIcons.class.getResourceAsStream("/icons/app-icon-" + size + ".png")) {
				if (stream != null) {
					icons.add(new Image(stream));
				}
			} catch (java.io.IOException exception) {
				// A missing or unreadable size only costs sharpness; the others still apply.
			}
		}
		return icons;
	}
}
