spring.application.name=gdrive-backup
google.oauth.client-secrets=${GOOGLE_OAUTH_CLIENT_SECRETS:}
google.service-account.key=${GOOGLE_SERVICE_ACCOUNT_KEY:}
google.drive.preview.user-email=${GOOGLE_IMPERSONATED_USER:}
